version: '3.8'

services:
  rbac-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=<your_password_here>
      - DB_NAME=rbac
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: <your_password_here>
      POSTGRES_DB: rbac
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: